
# conda install mamba -n base -c conda-forge

# mamba env create -f environment.yml
# mamba remove --name kedro --all -y
# mamba env update --file environment.yml --prune

name: kedro
channels:
  - default
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - openssl
  - future
  - more-itertools=9.0.0
  - ipython=7.33.0
  - orjson=3.8.1
  - h11
  - uvicorn=0.17.6
  - httpx=0.23.0
  - pandas=1.5.1
  - pillow=9.2.0
  - aiofiles=0.6.0
  - pytables=3.6.1
  - pytest-cov
  - conda-forge:jupyterlab-variableinspector
  - conda-forge:numpy=1.23.4
  - conda-forge:python-multipart=0.0.5
  - conda-forge:fastapi=0.66.1
  - conda-forge:kedro[pandas]=0.18.3
  - conda-forge:kedro-mlflow=0.11.4
  - conda-forge:minio=7.1.12
  - s3fs=2022.1.0
  - pip:
    - kedro-viz==5.1.1
    - kedro[pandas]
#variables:
#  HDF5_DIR: 'C:\Program Files\HDF_Group\HDF5\1.12.2'
  