# [reference](https://kedro.readthedocs.io/en/latest/04_user_guide/04_data_catalog.html)
# [datasets](https://kedro.readthedocs.io/en/latest/kedro.extras.datasets.html)

model:
  type: pickle.PickleDataSet # shortcut for kedro.extras.datasets.pickle.PickleDataSet
  filepath: ../data/pipelinex_pytorch/model/model.pickle

#train_dataset:
#  type: pipelinex.CSVLocalDataSet
#  filepath: ../data/pytorch/load/train_dataset.csv

#val_dataset:
#  type: pipelinex.CSVLocalDataSet
#  filepath: ../data/pytorch/load/val_dataset.csv

submission:
  type: pipelinex.CSVLocalDataSet
  filepath: ../data/pipelinex_pytorch/load/submission.csv

shap_image:
  type: pipelinex.ImagesLocalDataSet
  path: ../data/pipelinex_pytorch/model/shap_image
  save_args:
    suffix: .png
